In [3]:
import numpy as np
an_array = np.array([3, 33, 333])
type(an_array)



numpy.ndarray

**This is a text**

In [2]:
import numpy as np
an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [7]:
print(an_array[0])

3


In [3]:
print(an_array[0],an_array[1])

3 33


In [5]:
print(an_array.shape)

(3,)


In [6]:
# ndarrays are mutable
an_array[0] = 888

In [7]:
print(an_array)

[888  33 333]


In [8]:
#ndarrays are strongly typed

an_array[0] = 'hi'

ValueError: invalid literal for int() with base 10: 'hi'

In [14]:
another = np.array([[11, 12, 13],[21, 22, 23]])  # create a rank 2 array
print(another)  #print the array
print("the shape is 2 rows and 3 columns: ", another.shape)
print("assessing the elements (0,1), (0,2) and (1,0) of the array ", another[0,1], another[0,2], another[1,0])

[[11 12 13]
 [21 22 23]]
the shape is 2 rows and 3 columns:  (2, 3)
assessing the elements (0,1), (0,2) and (1,0) of the array  12 13 21


**Other ways of creating arrays**

In [15]:
import numpy as np

#create a 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1)

[[ 0.  0.]
 [ 0.  0.]]


In [16]:
#create a 2x2 array filled with value 9.0
ex2 = np.full((2,2), 9.0)
print(ex2)

[[ 9.  9.]
 [ 9.  9.]]


In [17]:
#create a 2x2 array with diagonal as 1s and others as zero
ex3 = np.eye(2,2)
print(ex3)

[[ 1.  0.]
 [ 0.  1.]]


In [21]:
#create an 1x2 array of all ones
ex4 = np.ones((1,2))
print(ex4)
print(ex4.shape)

[[ 1.  1.]]
(1, 2)


In [23]:
#create random array
ex5 = np.random.random((2,3))
print(ex5)

[[ 0.15081983  0.5524392   0.50464936]
 [ 0.85902921  0.44410319  0.00302729]]


## Array Indexing

*similer to the use of slice indexing with lists and strings, we can use the slice indexing to pull out subregions of ndarray

In [27]:
# create rank 2 array of shape(3,4)
import numpy as np
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


use subslicing to get a subarray consisting of 2 rows x 2 columns

In [28]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [34]:
a_slice[0,0] = 500
print(an_array , a_slice)

[[ 11 800  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]] [[500  13]
 [ 22  23]]


In [33]:
# an array can be created from a slice so that if you change the slice, the original array does not change
a_slice = np.array(an_array[:2, 1:3])
print(a_slice)

[[800  13]
 [ 22  23]]


## Use both integer indexing and slice indexing


In [36]:
#create a rank 2 array of shape(3,4)
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [37]:
#using both integer indexing and slicing generates array of lower rank
row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [38]:
#slicing alone generates array of same rank as the an_array
row_rank2 = an_array[1:2, :]
print(row_rank2)


[[21 22 23 24]]


In [39]:
#create a rank 2 array of shape(3,4)
an_array = np.array([[11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [42]:
#we can do same as above for cloumns
col_array1 = an_array[:, 1]
print(col_array1)
print(col_array1.shape)
col_array2 = an_array[:, 1:2]
print( col_array2, col_array2.shape)

[12 22 32]
(3,)
[[12]
 [22]
 [32]] (3, 1)


In [43]:
col_array1

array([12, 22, 32])

## Array Indexing for changing elements

some times it is useful to use an array of indexes to access to change elements

In [46]:
#create a rank 2 array of shape(4,3)
an_array = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
print('Original array')
print(an_array, an_array.shape)

Original array
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]] (4, 3)


In [48]:
#create an array of indices
col_indices = np.array([0, 1, 2, 0])
print('\nCol Indices picked: ', col_indices)
row_indices = np.arange(4)
print('\nRow Indices picked: ', row_indices)



Col Indices picked:  [0 1 2 0]

Row Indices picked:  [0 1 2 3]


In [49]:
#pairing of row_indices and col_indices
for row,col in zip(row_indices,col_indices):
    print(row, ',', col)

0 , 0
1 , 1
2 , 2
3 , 0


In [50]:
#select one element from each row
print('Value in array for those indices ', an_array[row_indices, col_indices])

Value in array for those indices  [11 22 33 41]


In [51]:
#change one element from each row using the indices selected
an_array[row_indices, col_indices] += 10000
print(an_array)

[[10011    12    13]
 [   21 10022    23]
 [   31    32 10033]
 [10041    42    43]]


In [53]:
an_array

array([[10011,    12,    13],
       [   21, 10022,    23],
       [   31,    32, 10033],
       [10041,    42,    43]])

## Boolean Indexing

### Array indexing for changing elements

In [54]:
#create a 3x2 array
an_array = np.array([[11, 12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [55]:
# create a filter which will be boolean values for weather each elements meet the given condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [58]:
# we can now select only those elements which meet the filetr criteria
print(an_array[filter])

[21 22 31 32]


In [62]:
filter = [(an_array > 20) & (an_array < 30)] 
filter
print(an_array[filter])

[21 22]


In [64]:
an_array[an_array % 2 == 0] += 1000
print(an_array)

[[  11 2012]
 [  21 2022]
 [  31 2032]]


## ndarrays data type and operations