In [3]:
import numpy as np
an_array = np.array([3, 33, 333])
type(an_array)



numpy.ndarray

**This is a text**

In [2]:
import numpy as np
an_array = np.array([3, 33, 333])
print(type(an_array))

<class 'numpy.ndarray'>


In [7]:
print(an_array[0])

3


In [3]:
print(an_array[0],an_array[1])

3 33


In [5]:
print(an_array.shape)

(3,)


In [6]:
# ndarrays are mutable
an_array[0] = 888

In [7]:
print(an_array)

[888  33 333]


In [8]:
#ndarrays are strongly typed

an_array[0] = 'hi'

ValueError: invalid literal for int() with base 10: 'hi'

In [14]:
another = np.array([[11, 12, 13],[21, 22, 23]])  # create a rank 2 array
print(another)  #print the array
print("the shape is 2 rows and 3 columns: ", another.shape)
print("assessing the elements (0,1), (0,2) and (1,0) of the array ", another[0,1], another[0,2], another[1,0])

[[11 12 13]
 [21 22 23]]
the shape is 2 rows and 3 columns:  (2, 3)
assessing the elements (0,1), (0,2) and (1,0) of the array  12 13 21


**Other ways of creating arrays**

In [ ]:
import